# @name upload
POST http://localhost:3333/videos/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name transcription
POST http://localhost:3333/videos/188bd0f6-9078-4274-83a2-142bcfa26c14/transcription
Content-Type: application/json

{
  "prompt": "What is the meaning of life?"
}